### PR TITLE
Fix error on Travis CI

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
This PR avoids [error](https://travis-ci.org/schneems/puma_worker_killer/builds/99007516) but it [failed](https://travis-ci.org/schneems/puma_worker_killer/jobs/105423203) yet... :broken_heart:

**Comment by schneems** [comment]
Why `gem update bundler` ?

**Comment by tricknotes** [comment]
Travis uses bundler 1.7.6 [by default](https://travis-ci.org/schneems/puma_worker_killer/jobs/99007517#L114).
```
$ bundle --version
Bundler version 1.7.6
```

However it is [not working](https://travis-ci.org/schneems/puma_worker_killer/jobs/99007517) with old rubygems (see for detail https://github.com/bundler/bundler/issues/3558 )

**Comment by tricknotes** [comment]
All tests are passed on https://github.com/schneems/puma_worker_killer/commit/e2c05a0603e6bc433a3802d8d58427878f8c8fe0.

**Pull request closed without merging**
