### PR TITLE
Test on recent rubies

### PR DESCRIPTION
**Pull request by misdoro**
Test on recent minor ruby versions, 
+ add 2.7.0
+ allow failure on 2.3.8

### CODE REVIEW

**Comment by misdoro** [comment]
@schneems I'm wondering if it would be better to migrate to github checks, something similar as puma did: https://github.com/puma/puma/blob/master/.github/workflows/ruby.yml

WDYT ?

**Comment by schneems** [comment]
> @schneems I'm wondering if it would be better to migrate to github checks, something similar to what puma did: https://github.com/puma/puma/blob/master/.github/workflows/ruby.yml

I'm for it. I'm not in love with travis. I believe though that 2.3.8 isn't present or there's some issues with it in github actions. My preference is CircleCI these days.

2.3.8 is working now. Can you update your PR to not remove it?

**Comment by misdoro** [comment]
Updated

**Comment by schneems** [comment]
thank you!

**Pull request merged**
