### PR TITLE
Add option to adjust restart randomizer 

### PR DESCRIPTION
**Pull request by SuperQ**
* Add option to adjust the rolling restart randomization.
* Increase the default random factor from 10 seconds to 300 seconds.
* Make sure rand() gets a float to avoid producing integer second.

### CODE REVIEW

**Comment by schneems** [comment]
Can we make it accept a range object instead of and end value. Also I would like the argument to be named `jitter_range`. 

If you're worried about it being a float we can also call `to_f` after the `rand()` call.

Can you also add some docs for using this to the README?

**Comment by SuperQ** [comment]
Sorry, this fell out of my inbox. I'm not sure what you're going for with the range object.

It doesn't seem like `.to_f` is necessary. As long as the `rand()` argument has a float argument, the output is a float.

**Comment by schneems** [comment]
What's the desire here? What is the end goal, did you run into a problem you're trying to address?

**Comment by SuperQ** [comment]
The goal is to avoid thundering herd and distributed clock synchronization problems by having randomized offsets.

**Comment by schneems** [comment]
I merged in some rubocop rules. Can you update your branch again? 

Locally this should fix things:

```
bundle exec rubocop --auto-correct
```

**Comment by SuperQ** [comment]
Whups, had some typos. Thanks!

**Comment by schneems** [comment]
Released in  v0.3.0

**Comment by SuperQ** [comment]
Nice! Thanks!

**Pull request merged**
